#
# Module manifest for module 'PerplexityXPC'
#
# Generated by: brianatalliance
# Generated on: 2026-03-27
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'PerplexityXPC.psm1'

# Version number of this module.
ModuleVersion = '1.0.0'

# Supported PSEditions
# CompatiblePSEditions = @()

# ID used to uniquely identify this module
GUID = 'a3f2e1d0-4b5c-6d7e-8f9a-0b1c2d3e4f5a'

# Author of this module
Author = 'brianatalliance'

# Company or vendor of this module
CompanyName = 'Alliance IT'

# Copyright statement for this module
Copyright = '(c) 2026 brianatalliance. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell module for PerplexityXPC broker - proxies requests to Perplexity Sonar API with MCP server management'

# Minimum version of the PowerShell engine required by this module
PowerShellVersion = '5.1'

# Name of the PowerShell host required by this module
# PowerShellHostName = ''

# Minimum version of the PowerShell host required by this module
# PowerShellHostVersion = ''

# Minimum version of Microsoft .NET Framework required by this module
# DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
# ClrVersion = ''

# Processor architecture (None, X86, Amd64) required by this module
# ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
# RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
FunctionsToExport = @(
    'Invoke-Perplexity',
    'Get-XPCStatus',
    'Get-XPCConfig',
    'Set-XPCConfig',
    'Get-McpServer',
    'Restart-McpServer',
    'Invoke-McpRequest',
    'Invoke-PerplexityFileAnalysis',
    'Invoke-PerplexityFolderAnalysis',
    'Invoke-PerplexityBatch',
    'Invoke-PerplexityReport',
    'Invoke-PerplexityTicketAnalysis',
    'Invoke-PerplexityDeviceAnalysis',
    'Invoke-PerplexitySecurityAnalysis'
)

# Cmdlets to export from this module
CmdletsToExport = @()

# Variables to export from this module
VariablesToExport = @()

# Aliases to export from this module
AliasesToExport = @()

# DSC resources to export from this module
# DscResourcesToExport = @()

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
PrivateData = @{

    PSData = @{

        # Tags applied to this module
        Tags = @('Perplexity', 'AI', 'MCP', 'IT', 'Atera', 'Intune', 'Security')

        # A URL to the license for this module.
        # LicenseUri = ''

        # A URL to the main website for this project.
        # ProjectUri = ''

        # A URL to an icon representing this module.
        # IconUri = ''

        # ReleaseNotes of this module
        ReleaseNotes = 'Initial release of PerplexityXPC PowerShell module.'

    } # End of PSData hashtable

} # End of PrivateData hashtable

}
